<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CSharpApp.Api\CSharpApp.Api.csproj" />
    <ProjectReference Include="..\..\CSharpApp.Application\CSharpApp.Application.csproj" />
    <ProjectReference Include="..\..\CSharpApp.Core\CSharpApp.Core.csproj" />
    <ProjectReference Include="..\..\CSharpApp.Infrastructure\CSharpApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
