<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.12.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configuration\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CSharpApp.Application\CSharpApp.Application.csproj" />
      <ProjectReference Include="..\CSharpApp.Core\CSharpApp.Core.csproj" />
    </ItemGroup>

</Project>
