<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mapster" />
        <PackageReference Include="Microsoft.Extensions.Configuration" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
        <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CSharpApp.Core\CSharpApp.Core.csproj" />
    </ItemGroup>

</Project>
