<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="System.Net" />
    <Using Include="System.Net.Http.Json" />
    <Using Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CSharpApp.Api\CSharpApp.Api.csproj" />
    <ProjectReference Include="..\..\CSharpApp.Core\CSharpApp.Core.csproj" />
    <ProjectReference Include="..\..\CSharpApp.Infrastructure\CSharpApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\CSharpApp.UnitTests\TestDoubles\TestJwt.cs" Link="TestDoubles\TestJwt.cs" />
  </ItemGroup>

</Project>
